### ISSUE TITLE
Testing DAO's Livepeer App functionality for approve / bond / claimEarnings / unbond / withdraw

### ISSUE THREAD

**Issue by chrishobcroft** [willjgriff/solidity-livepeer-aragon-app#2]
To test:

- "Approve Tokens" THEN "Bond to address"
- "Approve and bond Tokens to address"
- Call reward from node the Livepeer App has bonded to THEN ClaimEarnings
   - After 1 round
   - Claim 1 round after 2 rounds of earnings have accrued
- "Unbond tokens"
- Wait unbonding period then "Withdraw"
- Bond to a different address when already bonded to an address.
- Unbond without claiming

To validate information on Livepeer App within DAO, and also on explorer.livepeer.org

**Comment by chrishobcroft** [comment]
Observations / Notes:

- All tests performed as expected, aside from the minor niggle below!

- The big win here was demonstrating how a DAO can earn Inflationary Rewards by Bonding, Claiming, Unbonding then Withdrawing. This is a major milestone:

Here are the votes:

![image](https://user-images.githubusercontent.com/2212651/55431250-f9b75b80-5587-11e9-945d-4654a86722f6.png)

And here are the ERC-20 Token Transactions from Rinkeby Etherscan, showing rewards gained of 0.169 Rinkeby LPT:

![image](https://user-images.githubusercontent.com/2212651/55431338-28cdcd00-5588-11e9-9845-3c8041c08a84.png)

- Sometimes values didn't refresh, even when other values on the page had refreshed. See example in screenshot below - Unbonding Lock information had appeared, but Bonded tokens had not updated.

![Screenshot from 2019-04-02 20-22-46](https://user-images.githubusercontent.com/2212651/55430259-83195e80-5585-11e9-8a1a-f82998a33fa7.png)

- When testing "Bond to a different address when already bonded to an address.", something unexpected happened. Steps to recreate:
   - Bond 10 to Transcoder A (and wait for new round so that the Bond completes)
   - Bond 10 to Transcoder B
   - Result: 20 Bonded to Transcoder B. Expected: 10 Bonded to Transcoder B.

- Sometimes the votes didn't appear in the Voting app until I cleared the cookies and hard refreshed. This seemed more prevalent for claimearnings and unbond - although this part is more of a feeling :)

**Comment by willjgriff** [comment]
I'm not sure about the value's not refreshing, I changed some of the events triggering updates though so hopefully that's fixed now. Make another issue if it's observed again.

Bonding to a separate address a different amount actually increases the bonded amount by that much and changes the address bonded too. That's why if you want to just change the address you're bonded to, you bond 0 to the new address. So the outcome you've mentioned is expected behaviour.

Votes will not appear until they're associated transactions have been confirmed on the blockchain. Perhaps this is the issue. Unfortunately this isn't something I can influence.

Glad you consider this a big win though! I do too!
